# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RealGrid DEMO
subtitle: RealGrid 데모보기
email: support@realgrid.com
description: RealGrid 데모사이트 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "demo.realgrid.com" # the base hostname & protocol for your site
twitter_username: realgrid
github_username:  realgrid

# Build settings
markdown: kramdown
highlighter: rouge
# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  demos:
    output: true
    permalink: /:path/

logo:
  nav_mobile: '../images/logo-coralspace.svg'
  sidebar: '../images/icon-white.svg'
  url: 'http://www.realgrid.com'
  title: 'RealGrid'
  target: _new

nav_links:
  - title: Demo
    url: http://demo.realgrid.com
    partial: illustration-demo
    active: true
  - title: Tutorials
    url: http://help.realgrid.com/tutorial
    partial: illustration-tutorial
  - title: API Docs
    url: http://help.realgrid.com/apis
    partial: illustration-docs
  - title: Forums
    url: https://forums.meteor.com/
    partial: illustration-forums
    target: _new

sidebar_categories:
  Concept:
  Columns:
  Getting Started:
  Concepts:
  Columns:
  Rows:
  Data:
  Paging:
  Renderers:
  Series:
  Editing:
  Components:
  TreeView:
  Expression:
  Styles:
  DataCellStyle:
  Export:
  Import:
  Events:
  HighChart Interface:
  UbiReport Interface:
  Crownix Interface:
  Fusion Charts:
