#!/bin/sh

# 기존 빌드 제거
echo "---------------------"
echo " jekyll clean "
echo "---------------------"

jekyll clean


# 기존 빌드 제거
echo "---------------------"
echo " 배포 저장소 cloning "
echo "---------------------"

git clone https://github.com/RealGridSites/demo.git -o deploy _site/


# 실행환경으로 빌드한다.
echo "---------------------"
echo " jekyll build "
echo "---------------------"

# 리뷰를 위해 잠시 풀기
# JEKYLL_ENV=development jekyll build
JEKYLL_ENV=production jekyll build

# _site폴더가 생성되었다고 가정하고 실행
cd ./_site


echo "---------------------"
echo " check status"
echo "---------------------"

git status
git remote -v


# 혹시 _site가 재생성되어 remote가 제거되었다면 다시 생성하는 코드가 필요하다.
echo "---------------------"
echo " add to stage"
echo "---------------------"

git add -A


echo "---------------------"
echo " git commit "
echo "---------------------"

now=$(date +'%Y-%m-%d %T')
message="Update message $now"
git commit -m "$message"


echo "---------------------"
echo " git push"
echo "---------------------"

git push deploy gh-pages
